version: '3'
services:
  mongoserver:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  restapi:
    build: ./
    ports:
      - "5000:5000"
    links:
      - mongoserver
    depends_on:
      - mongoserver
